spring:
  application:
    name: AdminService
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${SPRING_LOCAL_PORT}
#eureka:
#  client:
#    service-url:
#        defaultZone: http://localhost:8761/eureka/