server:
    port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/security/**
        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/order/**
        - id: product-service
          uri: http://localhost:8092
          predicates:
              - Path=/api/v1/product/**
        - id: payment-service
          uri: http://localhost:8093
          predicates:
              - Path=/api/v1/payment/**
        - id: checkout-service
          uri: http://localhost:8094
          predicates:
              - Path=/api/v1/order/**
        - id: admin-service
          uri: http://localhost:8095
          predicates:
              - Path=/api/v1/admin/**