aws:
  s3:
    endpoint: https://s3.us-east-1.amazonaws.com
    region: us-east-1
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: online-shopping-team5
    reportPath: https://online-shopping-team5.s3.amazonaws.com/

report:
  path: src/main/resources/reports/
  returnUrl: https://online-shopping-team5.s3.amazonaws.com/

spring:
  application:
    name: ReportsService
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1.0
server:
  port: 8084