spring:
  application:
    name: OrderService
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQLDB_LOCAL_PORT}/${MYSQLDB_DATABASE}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

  zipkin:
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: localhost:9092

sleuth:
  sampler:
    probability: 1.0
server:
  port: ${SPRING_LOCAL_PORT}


eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/