spring:
  application:
    name: AdminService
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQLDB_DATABASE}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 9090
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/