spring:
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/customer/**
        - id: employee
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/employee/**
        - id: vendor
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/vendor/**
        - id: vendor-admin
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/vendor-admin/**
        - id: auth
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/auth/**
        - id: smtp
          uri: http://localhost:8088
          predicates:
              - Path=/api/v1/email/**
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/product/**
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cart/**
        - id: comment
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/comment/**
        - id: category
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/category/**
        - id: report
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/reports/**
        - id: reportTransaction
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/transaction/**
        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/cards/**
        - id: paymentTransaction
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/transactions/**
        - id: bank
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/banking/**

server:
  port: 8080

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

